import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home({ initialData }) {
	// https://stackoverflow.com/questions/62372471/nextjs-how-to-fetch-data-after-click-event
	// and
	// https://www.youtube.com/watch?v=U9T6YkEDkMo&t=2249s&ab_channel=DevEd
	const [data, setData] = useState(initialData);
	const [search, setSearch] = useState('');

	const onClick = async () => {
		const res = await fetch(
			`https://www.balldontlie.io/api/v1/players?search=lebron`
		);
		const newData = await res.json();

		return setData(newData.data);
	};

	const getPlayer = async e => {
		e.preventDefault();
		console.log(search);
		const res = await fetch(
			`https://www.balldontlie.io/api/v1/players?search=${search}`
		);
		const newData = await res.json();

		return setData(newData.data);
	};

	const onChange = e => {
		setSearch(e.target.value);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>NBA Players</h1>
				<button onClick={onClick}>Get LeBron</button>
				<form onSubmit={getPlayer}>
					<input
						type="text"
						name="player"
						placeholder="search for player"
						onChange={onChange}
						value={search}
					/>
					<button type="submit">Search</button>
				</form>
				<ul>
					{data.map(player => (
						<li key={player.id}>
							{player.first_name} {player.last_name} - {player.team.full_name}
						</li>
					))}
				</ul>
			</main>
		</div>
	);
}

export async function getStaticProps(context) {
	const res = await fetch(`https://www.balldontlie.io/api/v1/players`);
	const players = await res.json();

	return {
		props: { initialData: players.data },
	};
}
